-- GENERATED by scripts/generate-seed.mjs -- do not edit by hand.
-- Source: gigly-prototype.html (VENUES / ARTISTS / GIGS).
-- Venues are real Liverpool rooms; artists and gigs are invented.

-- map_x/map_y are the prototype's stylised hand-drawn positions, kept in case
-- that view ever comes back. lat/lng are real, from OpenStreetMap, and
-- google_place_id is what the map uses to fetch reviews live.
insert into public.venues
  (name, slug, area, capacity, map_x, map_y, lat, lng, google_place_id) values
  ('The Jacaranda', 'the-jacaranda', 'Ropewalks', 150, 270, 150, 53.4024301, -2.9795756, 'ChIJD1yBJiQhe0gRCJaNbWKrTh4'),
  ('The Shipping Forecast', 'the-shipping-forecast', 'Ropewalks', 200, 345, 180, 53.4025238, -2.9793737, 'ChIJYUK5IiQhe0gRge5OezzWqgU'),
  ('EBGBs', 'ebgbs', 'Ropewalks', 250, 290, 235, 53.4015947, -2.9785309, NULL),
  ('Kazimier Stockroom', 'kazimier-stockroom', 'Ropewalks', 100, 378, 255, 53.4023835, -2.9822026, 'ChIJMTd0xSUhe0gR1G77FFSwi-c'),
  ('Quarry', 'quarry', 'Hardman Street', 180, 460, 165, 53.4018204, -2.9724189, 'ChIJMQZDnTMhe0gRAX9CqciZ1Q0'),
  ('The Caledonia', 'the-caledonia', 'Georgian Quarter', 80, 505, 285, 53.4007666, -2.9700995, 'ChIJ5zUcGx8he0gR1k_clPBRj1Q'),
  ('24 Kitchen Street', '24-kitchen-street', 'Baltic Triangle', 400, 300, 365, 53.3973818, -2.9819296, 'ChIJXZ-T7Sche0gRHy9yN-iXEgU'),
  ('Future Yard', 'future-yard', 'Birkenhead', 280, 58, 295, 53.3911979, -3.0184714, 'ChIJd8JYLgcne0gRpegwtbxwKkY');

insert into public.artists
  (name, slug, genre, genre_group, from_area, bio, art_seed, art_palette, art_band) values
  ('Dock Leaf', 'dock-leaf', 'Indie rock', 'Indie'::public.genre_group, 'Wavertree', 'Two drummers, no bassist. Loud, tuneful, done in 25 minutes.', 11, 0, array['drums','guitar','mic','drums']::text[]),
  ('Marzipan Riot', 'marzipan-riot', 'Punk', 'Punk'::public.genre_group, 'Bootle', 'Three chords and a megaphone. Every song is about landlords.', 23, 1, array['guitar','mic','drums']::text[]),
  ('Velvet Ferry', 'velvet-ferry', 'Dream pop', 'Indie'::public.genre_group, 'Birkenhead', 'Reverb-heavy pop written on the 6:40 ferry to work.', 37, 2, array['synth','mic','guitar']::text[]),
  ('Low Tide Club', 'low-tide-club', 'Jazz', 'Jazz'::public.genre_group, 'Toxteth', 'Hard bop standards and originals, every other Sunday.', 41, 3, array['bass','drums','mic']::text[]),
  ('Nan''s Carpet', 'nans-carpet', 'Post-punk', 'Punk'::public.genre_group, 'Anfield', 'Spoken word over bass loops. First gig was in a launderette.', 53, 4, array['mic','guitar']::text[]),
  ('Ozone Layer Cake', 'ozone-layer-cake', 'Electronic', 'Electronic'::public.genre_group, 'Baltic Triangle', 'Hardware-only sets. Nothing is synced and it still works.', 67, 5, array['synth']::text[]),
  ('The Overheads', 'the-overheads', 'Indie', 'Indie'::public.genre_group, 'Allerton', 'The biggest small band in town, just back from a support tour.', 71, 1, array['guitar','mic','guitar','drums']::text[]),
  ('Sister Bootle', 'sister-bootle', 'Soul', 'Soul'::public.genre_group, 'Bootle', 'Seven-piece soul revue with a borrowed horn section.', 83, 3, array['mic','bass','synth','mic']::text[]),
  ('Halfway to Hoylake', 'halfway-to-hoylake', 'Folk', 'Folk'::public.genre_group, 'West Kirby', 'Two voices, one guitar, songs about the Wirral coast.', 97, 4, array['guitar','mic']::text[]),
  ('Kirkdale Static', 'kirkdale-static', 'Shoegaze', 'Indie'::public.genre_group, 'Kirkdale', 'Bring earplugs.', 101, 5, array['guitar','guitar','drums']::text[]),
  ('Tuebrook Tapes', 'tuebrook-tapes', 'Hip hop', 'Hip hop'::public.genre_group, 'Tuebrook', 'A producer and two MCs. Beats from charity-shop cassettes.', 113, 0, array['mic','synth','mic']::text[]),
  ('Pier Head Choir of One', 'pier-head-choir-of-one', 'Singer-songwriter', 'Folk'::public.genre_group, 'Aigburth', 'One woman, a loop pedal, twelve-part harmonies.', 127, 2, array['mic']::text[]);

-- Gigs are placed relative to the date the seed runs so the listing always
-- has something upcoming.
do $seed$
declare
  r        record;
  v_gig_id uuid;
  v_starts timestamptz;
  v_slug   text;
  i        integer;
begin
  for r in
    select * from (values
      ('the-jacaranda', 0, '19:30'::time, 600, array['dock-leaf','nans-carpet']::text[]),
      ('the-caledonia', 0, '20:00'::time, 0, array['low-tide-club']::text[]),
      ('24-kitchen-street', 0, '22:00'::time, 800, array['ozone-layer-cake','tuebrook-tapes']::text[]),
      ('quarry', 1, '19:00'::time, 500, array['kirkdale-static','dock-leaf']::text[]),
      ('future-yard', 1, '20:00'::time, 1000, array['velvet-ferry','halfway-to-hoylake']::text[]),
      ('ebgbs', 2, '19:30'::time, 700, array['marzipan-riot','nans-carpet','kirkdale-static']::text[]),
      ('kazimier-stockroom', 2, '18:00'::time, 0, array['pier-head-choir-of-one']::text[]),
      ('the-shipping-forecast', 3, '20:00'::time, 900, array['sister-bootle']::text[]),
      ('the-jacaranda', 4, '19:30'::time, 400, array['halfway-to-hoylake','pier-head-choir-of-one']::text[]),
      ('quarry', 5, '19:00'::time, 1200, array['the-overheads','dock-leaf']::text[]),
      ('24-kitchen-street', 5, '21:00'::time, 600, array['tuebrook-tapes']::text[]),
      ('the-caledonia', 6, '20:00'::time, 0, array['low-tide-club','sister-bootle']::text[]),
      ('future-yard', 9, '19:30'::time, 1000, array['marzipan-riot','velvet-ferry']::text[]),
      ('ebgbs', 16, '20:00'::time, 800, array['ozone-layer-cake']::text[]),
      ('the-shipping-forecast', -2, '19:30'::time, 600, array['marzipan-riot','dock-leaf']::text[]),
      ('future-yard', -6, '20:00'::time, 1200, array['the-overheads','kirkdale-static']::text[]),
      ('the-caledonia', -9, '20:00'::time, 0, array['low-tide-club']::text[])
    ) as t(venue_slug, day_offset, at_time, price_pence, lineup)
  loop
    v_starts := (((now() at time zone 'Europe/London')::date + r.day_offset) + r.at_time)
                  at time zone 'Europe/London';

    v_slug := r.lineup[1] || '-at-' || r.venue_slug || '-'
              || to_char(v_starts at time zone 'Europe/London', 'YYYY-MM-DD');

    insert into public.gigs (slug, venue_id, starts_at, price_pence, status)
    select v_slug, v.id, v_starts, r.price_pence, 'live'
    from public.venues v
    where v.slug = r.venue_slug
    returning id into v_gig_id;

    for i in 1 .. array_length(r.lineup, 1) loop
      insert into public.gig_artists (gig_id, artist_id, position)
      select v_gig_id, a.id, i - 1
      from public.artists a
      where a.slug = r.lineup[i];
    end loop;
  end loop;
end
$seed$;
