/**
 * Generates supabase/seed.sql from the prototype's VENUES / ARTISTS / GIGS.
 *
 * Run: node scripts/generate-seed.mjs
 *
 * Gig times are emitted as offsets from the date the seed runs, not fixed
 * dates, so `npm run db:reset` always produces a listing with gigs still to
 * come. Without that the seed rots and the chart empties out after a week.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const data = JSON.parse(readFileSync(join(here, "prototype-data.json"), "utf8"));

/** SQL string literal. */
const q = (s) => (s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`);

/** URL slug. Apostrophes are dropped rather than hyphenated: nans-carpet. */
const slugify = (s) =>
  s
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const artistSlug = new Map(data.ARTISTS.map((a) => [a.id, slugify(a.name)]));
const venueSlug = new Map(data.VENUES.map((v) => [v.id, slugify(v.name)]));

// --- sanity checks: a duplicate slug would silently drop a row ------------
for (const [label, slugs] of [
  ["artist", [...artistSlug.values()]],
  ["venue", [...venueSlug.values()]],
]) {
  const dupes = slugs.filter((s, i) => slugs.indexOf(s) !== i);
  if (dupes.length) throw new Error(`duplicate ${label} slugs: ${dupes.join(", ")}`);
}

const groups = new Set(["Indie", "Punk", "Jazz", "Electronic", "Folk", "Soul", "Hip hop"]);
for (const a of data.ARTISTS) {
  if (!groups.has(a.group)) throw new Error(`${a.name}: unknown genre_group ${a.group}`);
}

const bands = new Set(["guitar", "mic", "synth", "bass", "drums"]);
for (const a of data.ARTISTS) {
  for (const b of a.band) if (!bands.has(b)) throw new Error(`${a.name}: unknown band part ${b}`);
}

// --- venues ----------------------------------------------------------------
const venues = data.VENUES.map(
  (v) =>
    `  (${q(v.name)}, ${q(venueSlug.get(v.id))}, ${q(v.area)}, ${v.cap}, ${v.x}, ${v.y})`,
).join(",\n");

// --- artists ---------------------------------------------------------------
const artists = data.ARTISTS.map((a) => {
  const band = `array[${a.band.map((b) => q(b)).join(",")}]::text[]`;
  return `  (${q(a.name)}, ${q(artistSlug.get(a.id))}, ${q(a.genre)}, ${q(a.group)}::public.genre_group, ${q(a.from)}, ${q(a.blurb)}, ${a.seed}, ${a.pal}, ${band})`;
}).join(",\n");

// --- gigs ------------------------------------------------------------------
// Negative day offsets are gigs that have already happened. They stay in the
// seed on purpose: they prove hyping closes once a gig starts, and they give
// venue pages some history.
const gigs = data.GIGS.map((g) => {
  const lineup = `array[${g.lineup.map((id) => q(artistSlug.get(id))).join(",")}]::text[]`;
  return `      (${q(venueSlug.get(g.venue))}, ${g.day}, ${q(g.time)}::time, ${g.price * 100}, ${lineup})`;
}).join(",\n");

const sql = `-- GENERATED by scripts/generate-seed.mjs -- do not edit by hand.
-- Source: gigly-prototype.html (VENUES / ARTISTS / GIGS).
-- Venues are real Liverpool rooms; artists and gigs are invented.

-- Venue lat/lng are deliberately left NULL. The prototype only has positions
-- on its stylised hand-drawn map, which is not geographic, and inventing
-- plausible-looking coordinates for real venues would be worse than having
-- none. Populate from a real source (OSM/Places) when the map needs it.
insert into public.venues (name, slug, area, capacity, map_x, map_y) values
${venues};

insert into public.artists
  (name, slug, genre, genre_group, from_area, bio, art_seed, art_palette, art_band) values
${artists};

-- Gigs are placed relative to the date the seed runs so the listing always
-- has something upcoming.
do $seed$
declare
  r        record;
  v_gig_id uuid;
  v_starts timestamptz;
  v_slug   text;
  i        integer;
begin
  for r in
    select * from (values
${gigs}
    ) as t(venue_slug, day_offset, at_time, price_pence, lineup)
  loop
    v_starts := (((now() at time zone 'Europe/London')::date + r.day_offset) + r.at_time)
                  at time zone 'Europe/London';

    v_slug := r.lineup[1] || '-at-' || r.venue_slug || '-'
              || to_char(v_starts at time zone 'Europe/London', 'YYYY-MM-DD');

    insert into public.gigs (slug, venue_id, starts_at, price_pence, status)
    select v_slug, v.id, v_starts, r.price_pence, 'live'
    from public.venues v
    where v.slug = r.venue_slug
    returning id into v_gig_id;

    for i in 1 .. array_length(r.lineup, 1) loop
      insert into public.gig_artists (gig_id, artist_id, position)
      select v_gig_id, a.id, i - 1
      from public.artists a
      where a.slug = r.lineup[i];
    end loop;
  end loop;
end
$seed$;
`;

writeFileSync(join(root, "supabase", "seed.sql"), sql);

const upcoming = data.GIGS.filter((g) => g.day >= 0).length;
console.log(
  `supabase/seed.sql written: ${data.VENUES.length} venues, ${data.ARTISTS.length} artists, ` +
    `${data.GIGS.length} gigs (${upcoming} upcoming, ${data.GIGS.length - upcoming} past)`,
);
